// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"GOZEROTEST/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/book/id/:bookId",
				Handler: GetBookDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/book/list",
				Handler: GetBookListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/book/create",
				Handler: AddBookHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/book/del",
				Handler: DelBookHandler(serverCtx),
			},
		},
	)
}
